#!/bin/sh
set -o nounset
if [ -f testData/genPeaks$1 ]
then
  python testMainSetK.py testData/genPeaks$1 testData/clusteredGenPeaks$1 $2
else
  echo "Usage: $0 <ID of existing genPeaks data> <number of k to hold clustering to>"
  exit
fi